export const Movies = [
    { title:`Conjuring 3`,
    description:`sous l'emprise du diable retrace une affaire terrifiante de meurtre et de présence maléfique mystérieuse qui a même ébranlé les enquêteurs paranormaux Ed et Lorraine Warren, pourtant très aguerris. Dans cette affaire issue de leurs dossiers secrets – l'une des plus spectaculaires – , Ed et Lorrain commencent par se battre pour protéger l'âme d'un petit garçon, puis basculent dans un monde radicalement inconnu. Ce sera la première fois dans l'histoire des États-Unis qu'un homme soupçonné de meurtre plaide la possession démoniaque comme ligne de défense.`, 
    posterURL:`https://media.melty.fr/article-4020807-ajust_768/media.jpg`,
    rating:3},
    { title:`The Father`,
    description:`Alors qu’il vieillit et devient de moins en moins autonome, un père refuse l’aide de sa fille. Voyant la situation se dégrader, il commence à douter de ses proches, de son propre esprit et même de ce qui est réel.`, 
    posterURL:`https://fr.web.img3.acsta.net/pictures/21/05/06/12/38/3783901.jpg`,
    rating:4,},
    { title:`Les Mitchell contre les machines`,
    description:`Katie Michell, jeune fille passionnée à la créativité débordante, est acceptée dans l'université de ses rêves. Alors qu’elle avait prévu de prendre l’avion pour s’installer à l’université, son père Rick, grand amoureux de la nature, décide que toute la famille devrait l’accompagner en voiture pour faire un road- trip mémorable et profiter d’un moment tous ensemble. Linda, mère excessivement positive, Aaron, petit frère excentrique, et Monchi, carlin délicieusement joufflu, se joignent à Katie et Rick pour un ultime voyage en famille. Mais le programme des Mitchell est soudainement interrompu par une rébellion technologique : partout dans le monde, les appareils électroniques tant appréciés de tous – des téléphones aux appareils électroménagers, en passant par des robots personnels innovants – décident qu’il est temps de prendre le contrôle. Avec l’aide de deux robots dysfonctionnels, les Mitchell vont devoir surmonter leurs problèmes et travailler ensemble pour s’en sortir et sauver le monde !`, 
    posterURL:`https://media.senscritique.com/media/000020042211/source_big/Les_Mitchell_contre_les_machines.jpg`,
    rating:2,
  },
  ];